AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda stack with VPC config using parameters

Parameters:
  PublicSubnet1Id:
    Type: String
    Description: Subnet ID for Lambda function

  LambdaSecurityGroupId:
    Type: String
    Description: Security Group ID for Lambda function

Resources:
  HelloWorldFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: modular-hello-world
      Runtime: python3.13
      Handler: index.lambda_handler
      Role: arn:aws:iam::148761664911:role/modular-lambda-role
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {
                  "statusCode": 200,
                  "body": "Modification adding subnet to VPC and associate it to this lambda 🚀"
              }
      VpcConfig:
        SubnetIds:
          - !Ref PublicSubnet1Id
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId

