AWSTemplateFormatVersion: '2010-09-09'
Description: Root CloudFormation template with modular includes

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket containing the nested templates

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://${BucketName}.s3.amazonaws.com/vpc.yaml

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://${BucketName}.s3.amazonaws.com/lambda.yaml

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://${BucketName}.s3.amazonaws.com/rds.yaml


        
#templates/
#│
#├── root.yaml           <- The root for changes 
#├── vpc.yaml
#├── lambda.yaml
#├── rds.yaml
