AWSTemplateFormatVersion: '2010-09-09'
Description: Root CloudFormation template with modular includes

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket containing the nested templates

  CreateDB:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"
    Description: Whether to create the RDS database stack or skip it if it already exists

Conditions:
  ShouldCreateDB: !Equals [!Ref CreateDB, "true"]

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://${BucketName}.s3.amazonaws.com/vpc.yaml

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL:
        Fn::Sub: https://${BucketName}.s3.amazonaws.com/lambda.yaml
      Parameters:
        VpcId: !ImportValue ModularVPC-VpcId
        PublicSubnet1Id: !ImportValue ModularVPC-PublicSubnet1Id
        LambdaSecurityGroupId: !ImportValue ModularVPC-LambdaSecurityGroupId

  RDSStack:
    Condition: ShouldCreateDB
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://${BucketName}.s3.amazonaws.com/rds.yaml


        
#templates/
#│
#├── root.yaml           <- The root for changes 
#├── vpc.yaml
#├── lambda.yaml
#├── rds.yaml
