AWSTemplateFormatVersion: '2010-09-09'
Description: Stack para crear un bucket S3 y un rol IAM simple

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "my-github-actions-bucket-${AWS::Region}-${AWS::AccountId}"

  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubDeployRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole

