name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file templates/s3-iam-template.yml \
            --stack-name my-github-cf-stack \
            --capabilities CAPABILITY_NAMED_IAM

